# Generated by Django 4.1 on 2022-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_name_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
