# Generated by Django 4.1 on 2022-08-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_linkmodel_alter_profilemodel_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='link',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='link',
            field=models.ManyToManyField(blank=True, to='users.linkmodel'),
        ),
    ]
