# Generated by Django 4.1 on 2022-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profilemodel_link_profilemodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='link_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
