# Generated by Django 4.1 on 2022-08-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_linkmodel_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='link',
            new_name='profile_link',
        ),
    ]
