# Generated by Django 4.1 on 2022-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stories', '0003_book_writer_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.ManyToManyField(blank=True, to='users.profilemodel'),
        ),
        migrations.AddField(
            model_name='book',
            name='about_who',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='stories.author'),
        ),
    ]
