# Generated by Django 4.1 on 2022-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_book_about_book_about_who_alter_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
